modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/FinnSetchell/MoogsSoaringStructures/issues" #optional
license="https://github.com/FinnSetchell/MoogsSoaringStructures/blob/1.20-MultiLoader/LICENSE"

[[mods]]
    modId="mss"
    logoFile= "assets/mss/icon.png"
    logoBlur=false
    version="${version}"
    displayName="Moog's Soaring Structures"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-soaring-structures"
    authors="FinnDog"
    credits="Thanks to the builders and contributors as well as TelepathicGrunt for their structure mod template and rs"
    description='''
    Moogs Soaring Structures brings life, fun and variety to your Minecraft world!
    Explore awesome new structures made with vanilla blocks and entities, and discover loot,
    enemies, and villagers along the way. This mod is compatible with any modpack and keeps
    the vanilla feel of the game!
    '''

[[mixins]]
    config = "mss-neoforge.mixins.json"

[[mixins]]
    config = "mss-common.mixins.json"

[[dependencies.mss]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,)"